version: '2'
volumes:
  my-db:

services:
  app:
    image: 'docker-todo-app:latest'
    ports:
      - 8080:8080
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/todos?autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=todouser
      - SPRING_DATASOURCE_PASSWORD=dummytodos
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

  db:
    image: 'mysql:8-oracle'
    restart: always
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_DATABASE: todos
      MYSQL_USER: todouser
      MYSQL_PASSWORD: dummytodos
      MYSQL_ROOT_PASSWORD: todopassword
    volumes:
      - my-db:/var/lib/mysql

